FROM nginx:latest

# Установка Docker CLI для получения логов
RUN apt-get update && \
    apt-get install -y docker.io

# Копирование скрипта entrypoint и конфига Nginx
COPY entrypoint.sh /entrypoint.sh
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]