name: Build, Test and Publish Helm chart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка зависимостей
        run: sudo apt update && sudo apt install -y cmake libgtest-dev

      - name: Сборка GTest
        run: |
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Конфигурация CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Сборка проекта
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Запуск тестов
        working-directory: ${{github.workspace}}/build
        run: ./git_tests

      - name: Установка Helm
        uses: azure/setup-helm@v3

      - name: Упаковка Helm-чарта
        run: |
          mkdir -p packaged-chart
          helm package helm/test-repo-chart -d packaged-chart

      - name: Публикация Helm-чарта в GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: packaged-chart/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
