name: Docker Build, Push and Helm Chart Publish

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]  

env:
  DOCKER_HUB_REPO: vchernodolya/githw

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write   
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push App image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.app
          push: true
          tags: ${{ env.DOCKER_HUB_REPO }}-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Web image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.web
          push: true
          tags: ${{ env.DOCKER_HUB_REPO }}-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm chart
        run: |
          mkdir -p packaged-chart
          helm package helm/test-repo-chart -d packaged-chart

      - name: Create GitHub Release and Upload Chart
        uses: softprops/action-gh-release@v1
        with:
          files: packaged-chart/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
